############# English navigation ##############

# main menu
[[main]]
weight = 1
name = "How We Help You"
hasChildren = true

[[main]]
name = "Meet Interstellar"
weight = 2
hasChildren = true

[[main]]
parent = "Knowledge Center"
name = "Success Stories"
url = "/case-studies/"
weight = 1

[[main]]
parent = "Knowledge Center"
name = "Blog"
url = "blog/"
weight = 3

[[main]]
parent = "Meet Interstellar"
name = "Interstellar Cares"
url = "interstellar_cares/"
weight = 2

[[main]]
parent = "Meet Interstellar"
name = "Careers"
url = "careers/"
weight = 3

[[main]]
name = "Knowledge Center"
url = "blog/"
hasChildren = true
weight = 3

[[main]]
parent = "How We Help You"
name = "Get More Business"
weight = 1

[[main]]
parent = "How We Help You"
name = "Digital Advertising"
url = "digital-advertising/"

[[main]]
parent = "How We Help You"
name = "Website Development"
url = "website-development/"

[[main]]
parent = "How We Help You"
name = "Search Engine Ranking"
url = "search-engine-ranking/"

[[main]]
parent = "How We Help You"
name = "Content Marketing"
url = "content-marketing/"

[[footer_01]]
name = "Interstellar Cares"
url = "interstellar_cares/"
weight = 2

[[footer_01]]
name = "Knowledge Center"
url = "blog/"
weight = 3

[[footer_02]]
name = "Get Started"
url = "contact/"
weight = 2